#!/usr/bin/env python3
"""Concatenate the mykb project into two hierarchically structured markdown files:
  - mykb-code.md   (scripts, configs, build files, viewer)
  - mykb-content.md (wiki articles, entities, domain pages, logs)

Usage: python3 build-export.py [--code-only] [--content-only] [--max-size-kb 500]
"""

import os, sys, re, json
from pathlib import Path

BUNDLE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = BUNDLE

# ── File classification ──────────────────────────────────────────
CODE_EXTENSIONS = {'.py', '.js', '.sh', '.json', '.html', '.css', '.yml', '.yaml', '.conf', '.ini', '.cfg', '.toml'}
CONTENT_EXTENSIONS = {'.md'}

# Subdirectories that are content vs code
CODE_SUBDIRS = {'.wiki-daemon', 'hooks', 'templates'}
CONTENT_SUBDIRS = {'wiki', 'ops', 'daily', 'raw'}

# Files at root that are code
ROOT_CODE_FILES = {'server.py', 'index.html', 'build-export.py', 'start.sh'}
ROOT_CONTENT_FILES = {'index.md', 'Home.md', 'README.md', 'log.md', 'AGENTS.md'}

EXCLUDE_DIRS = {'__pycache__', 'node_modules', '.git', '.okf-skill', '.obsidian'}
EXCLUDE_FILES = {'mykb-code.md', 'mykb-content.md', 'package-lock.json'}
BINARY_EXTS = {'.npz', '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico', '.woff', '.woff2', '.ttf', '.eot', '.DS_Store'}

MAX_SIZE_KB = int(os.environ.get('EXPORT_MAX_SIZE_KB', '500'))

def classify_file(rel_path):
    """Return 'code', 'content', or None."""
    parts = rel_path.replace('\\', '/').split('/')
    name = parts[-1]
    ext = os.path.splitext(name)[1].lower()
    
    if ext in BINARY_EXTS:
        return None
    if name in EXCLUDE_FILES:
        return None
    
    # Root files
    if len(parts) == 1:
        if name in ROOT_CODE_FILES:
            return 'code'
        if name in ROOT_CONTENT_FILES:
            return 'content'
        if ext == '.md':
            return 'content'
        if ext in CODE_EXTENSIONS:
            return 'code'
        return None
    
    # Check subdirectory prefix
    top_dir = parts[0]
    if top_dir in CODE_SUBDIRS:
        return 'code' if ext in CODE_EXTENSIONS or ext == '.md' else None
    if top_dir in CONTENT_SUBDIRS:
        return 'content' if ext == '.md' else None
    
    # Templates are code
    if 'templates' in parts:
        return 'code' if ext == '.md' else None
    
    # Everything else with code extensions
    if ext in CODE_EXTENSIONS:
        return 'code'
    if ext == '.md':
        return 'content'
    
    return None

def format_size(size_bytes):
    if size_bytes < 1024:
        return f'{size_bytes}B'
    elif size_bytes < 1024 * 1024:
        return f'{size_bytes / 1024:.1f}KB'
    else:
        return f'{size_bytes / 1024 / 1024:.1f}MB'

def fmt_header(text, level=1):
    return f'\n{"#" * level} {text}\n\n'

def safe_filename(name):
    """Sanitize a filename for use as an anchor."""
    s = name.replace('_', ' ').replace('-', ' ').replace('.', ' ')
    return re.sub(r'[^a-zA-Z0-9 ]', '', s).strip().title().replace(' ', '-').lower()

def build_export():
    code_files = []
    content_files = []
    
    for root, dirs, files in os.walk(BUNDLE):
        # Skip excluded dirs
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS and not d.startswith('.git')]
        
        for fn in sorted(files):
            fpath = os.path.join(root, fn)
            rel = os.path.relpath(fpath, BUNDLE)
            
            if fn in EXCLUDE_FILES:
                continue
            
            cls = classify_file(rel)
            if cls is None:
                continue
            
            size = os.path.getsize(fpath)
            if size > MAX_SIZE_KB * 1024:
                continue
            if size == 0:
                continue
            
            entry = (rel, fpath, size)
            if cls == 'code':
                code_files.append(entry)
            else:
                content_files.append(entry)
    
    return code_files, content_files

def write_section(fh, entries, title, emoji):
    fh.write(fmt_header(f'{emoji} {title}', 1))
    fh.write(f'\n> **{len(entries)} files** — Generated by build-export.py\n>\n')
    fh.write('> Use `# File: path/to/file` to locate each file in the hierarchy.\n\n')
    
    # Group by top-level directory
    groups = {}
    for rel, fpath, size in entries:
        parts = rel.replace('\\', '/').split('/')
        if len(parts) == 1:
            group = '(root)'
        else:
            group = parts[0]
        groups.setdefault(group, []).append((rel, fpath, size))
    
    for group in sorted(groups.keys()):
        group_entries = groups[group]
        fh.write(fmt_header(f'{group}/', 2))
        fh.write(f'*{len(group_entries)} files*\n\n')
        
        for rel, fpath, size in sorted(group_entries, key=lambda x: x[0]):
            size_str = format_size(size)
            fh.write(f'### 📄 `{rel}`  [{size_str}]\n\n')
            fh.write(f'<a id="file-{safe_filename(rel)}"></a>\n\n')
            
            try:
                with open(fpath, 'r', encoding='utf-8', errors='replace') as f:
                    text = f.read()
                
                # Detect language for code fence
                ext = os.path.splitext(rel)[1].lower()
                lang_map = {
                    '.py': 'python',
                    '.js': 'javascript',
                    '.sh': 'bash',
                    '.json': 'json',
                    '.html': 'html',
                    '.css': 'css',
                    '.yml': 'yaml',
                    '.yaml': 'yaml',
                    '.md': 'markdown',
                    '.toml': 'toml',
                    '.conf': 'ini',
                    '.ini': 'ini',
                }
                lang = lang_map.get(ext, '')
                
                fh.write(f'```{lang}\n')
                fh.write(text)
                if not text.endswith('\n'):
                    fh.write('\n')
                fh.write('```\n\n')
                
            except Exception as e:
                fh.write(f'*Error reading file: {e}*\n\n')

def main():
    code_only = '--code-only' in sys.argv
    content_only = '--content-only' in sys.argv
    
    global MAX_SIZE_KB
    for arg in sys.argv:
        if arg.startswith('--max-size-kb='):
            MAX_SIZE_KB = int(arg.split('=')[1])
    
    print(f"Scanning {BUNDLE}...")
    code_files, content_files = build_export()
    
    print(f"  Code files:    {len(code_files)}")
    print(f"  Content files: {len(content_files)}")
    
    if not code_only:
        out_path = os.path.join(OUT_DIR, 'mykb-content.md')
        print(f"  Writing {out_path}...")
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write('# mykb — Content Export\n\n')
            f.write(f'*Generated {__import__("datetime").datetime.now().isoformat()[:10]}*\n\n')
            f.write('## Table of Contents\n\n')
            for rel, fpath, size in sorted(content_files, key=lambda x: x[0]):
                name = rel.replace('\\', '/')
                f.write(f'- [{name}](#file-{safe_filename(name)})\n')
            f.write('\n---\n')
            write_section(f, content_files, 'Wiki Content', '📝')
        
        size = os.path.getsize(out_path)
        print(f"  → {format_size(size)}")
    
    if not content_only:
        out_path = os.path.join(OUT_DIR, 'mykb-code.md')
        print(f"  Writing {out_path}...")
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write('# mykb — Code Export\n\n')
            f.write(f'*Generated {__import__("datetime").datetime.now().isoformat()[:10]}*\n\n')
            f.write('## Table of Contents\n\n')
            for rel, fpath, size in sorted(code_files, key=lambda x: x[0]):
                name = rel.replace('\\', '/')
                f.write(f'- [{name}](#file-{safe_filename(name)})\n')
            f.write('\n---\n')
            write_section(f, code_files, 'Project Code', '⚙️')
        
        size = os.path.getsize(out_path)
        print(f"  → {format_size(size)}")
    
    total_orig = sum(s for _, _, s in code_files + content_files)
    print(f"\n  Total source size: {format_size(total_orig)}")
    print("Done!")

if __name__ == '__main__':
    main()
