"""L2 — Per-Session Improvement Loop.

The middle loop: generate code improvements → submit to evaluator →
on approval: apply, checkpoint, update memory.
On rejection: discard, log failure pattern.

Phase 4: integrated with Budget, RecoveryManager, and ResourceEnforcer.
"""

import json
import logging
import time
from dataclasses import dataclass, field
from typing import Any, Optional

from rsis.checkpoint import CheckpointManager
from rsis.config import CONFIG
from rsis.evaluator import EvalResult, EvaluatorClient
from rsis.loop_l1 import L1ActionLoop, L1Result, ToolCall
from rsis.pipeline import DAGWorkerPool
from rsis.recovery import RecoveryManager
from rsis.scheduler import AgentScheduler, Priority
from rsis.telemetry import TelemetryCollector, TelemetryEvent
from rsis.timeout import Budget, TimeoutError

logger = logging.getLogger(__name__)


@dataclass
class ImprovementCandidate:
    """A candidate improvement generated by L2."""
    description: str
    target_files: list[str]
    diff_or_code: str
    rationale: str
    metadata: dict = field(default_factory=dict)


@dataclass
class L2Result:
    """Outcome of an L2 improvement session."""
    success: bool
    attempts: int = 0
    eval_results: list[EvalResult] = field(default_factory=list)
    candidates: list[ImprovementCandidate] = field(default_factory=list)
    applied: Optional[ImprovementCandidate] = None
    error: Optional[str] = None


class L2ImprovementLoop:
    """Per-session improvement loop with evaluator gate."""

    def __init__(
        self,
        telemetry: TelemetryCollector,
        evaluator: Optional[EvaluatorClient] = None,
        checkpoint_mgr: Optional[CheckpointManager] = None,
        l1_loop: Optional[L1ActionLoop] = None,
        recovery: Optional[RecoveryManager] = None,
    ):
        self.config = CONFIG.l2
        self.telemetry = telemetry
        self.evaluator = evaluator or EvaluatorClient()
        self.checkpoint = checkpoint_mgr or CheckpointManager(CONFIG.workspace_dir)
        self.l1 = l1_loop
        self.recovery = recovery or RecoveryManager(checkpoint_mgr=self.checkpoint)

    def run_session(
        self, goal: str, budget: Optional[Budget] = None
    ) -> L2Result:
        """Run an L2 improvement session within a budget.

        Generates up to `max_improvement_attempts` candidates, evaluates each,
        and applies the first one that passes.
        """
        budget = budget or Budget(
            max_iterations=self.config.max_improvement_attempts,
            max_time_s=self.config.session_timeout_s,
            label="L2 session",
        )

        logger.info("L2 session starting — goal: %s", goal[:80])
        self.telemetry.record(TelemetryEvent(
            event_type="l2_start", metadata={"goal": goal},
        ))

        parallel = self.config.parallel_candidates
        if parallel and parallel > 1:
            return self._run_parallel_session(goal, budget)

        eval_results: list[EvalResult] = []
        candidates: list[ImprovementCandidate] = []
        applied: Optional[ImprovementCandidate] = None

        while budget.tick():
            attempt = budget.iterations
            logger.info("L2 attempt %d/%d", attempt, budget.max_iterations)

            try:
                # 1. Generate candidate improvement
                candidate = self._generate_candidate(goal, attempt, eval_results)
                candidates.append(candidate)

                self.telemetry.record(TelemetryEvent(
                    event_type="l2_candidate",
                    metadata={
                        "attempt": attempt,
                        "target_files": candidate.target_files,
                        "description": candidate.description,
                    },
                ))

                # 2. Checkpoint before submitting to evaluator
                if CONFIG.checkpoint_before_mutation:
                    self.checkpoint.checkpoint(f"l2-candidate-{attempt}")

                # 3. Submit to evaluator
                eval_result = self.evaluator.evaluate({
                    "description": candidate.description,
                    "target_files": candidate.target_files,
                    "diff": candidate.diff_or_code,
                    "rationale": candidate.rationale,
                    "attempt": attempt,
                    "goal": goal,
                })
                eval_results.append(eval_result)

                self.telemetry.record(TelemetryEvent(
                    event_type="l2_evaluation",
                    metadata={
                        "attempt": attempt,
                        "decision": eval_result.decision,
                        "score_avg": eval_result.score_avg,
                    },
                ))

                # 4. On approval: apply, checkpoint, return
                if eval_result.passed:
                    logger.info("L2 candidate approved on attempt %d", attempt)
                    try:
                        self._apply_improvement(candidate)
                        self.checkpoint.checkpoint(
                            f"l2-applied-{attempt}-{candidate.description[:30]}"
                        )
                        applied = candidate
                        self.recovery.reset_failure_count()
                    except Exception as e:
                        logger.error("Failed to apply improvement: %s", e)
                        self.recovery.record_failure()
                        self.recovery.rollback_on_failure("apply_improvement")
                    break
                else:
                    logger.info("L2 candidate rejected: %s",
                                eval_result.rationale[:60])

            except TimeoutError:
                raise
            except Exception as e:
                logger.error("L2 attempt %d failed: %s", attempt, e)
                self.recovery.record_failure()
                continue

        success = applied is not None
        if not success and budget.expired:
            logger.warning("L2 budget exhausted without success")
            self.recovery.record_failure()

        self.telemetry.record(TelemetryEvent(
            event_type="l2_complete",
            metadata={"success": success, "attempts": len(eval_results)},
        ))

        return L2Result(
            success=success,
            attempts=len(eval_results),
            eval_results=eval_results,
            candidates=candidates,
            applied=applied,
        )

    # ── Multi-agent parallel session (DAG fan-out/fan-in) ───────────── #

    def _run_parallel_session(self, goal: str,
                              budget: Budget) -> L2Result:
        """Fan-out N candidate coders, fan-in through the evaluator gate.

        DAG: planner → N parallel coders → fan-in reviewer. The review wave
        runs through the AgentScheduler so repeated coder↔reviewer hand-offs
        are depth/cycle guarded instead of spinning. The immutable evaluator
        remains the gate: only a PASS candidate is applied.
        """
        n = max(2, min(int(self.config.parallel_candidates),
                       budget.max_iterations))
        logger.info("L2 parallel session: %d candidates (fan-out)", n)
        self.telemetry.record(TelemetryEvent(
            event_type="l2_parallel_start",
            metadata={"goal": goal, "candidates": n},
        ))

        pool = DAGWorkerPool(num_workers=min(n, 4),
                             on_event=self._dag_event,
                             max_retries=self.config.parallel_retries)
        pool.add_task("planner", "planner", {"goal": goal})
        for i in range(n):
            pool.add_task(f"coder-{i}", "coder", {"attempt": i + 1},
                          depends_on=["planner"])
        pool.add_task("fanin", "fanin",
                      {}, depends_on=[f"coder-{i}" for i in range(n)])

        def run(task):
            if task.role == "planner":
                return {"goal": goal, "count": n}
            if task.role == "coder":
                if not budget.tick():
                    raise TimeoutError("L2 parallel budget exhausted")
                return self._generate_candidate(
                    goal, task.payload["attempt"], [])
            if task.role == "fanin":
                candidates = [pool.tasks[f"coder-{i}"].result
                              for i in range(n)]
                candidates = [c for c in candidates if c is not None]
                return self._review_candidates(goal, candidates)
            raise RuntimeError(f"unknown DAG role: {task.role}")

        try:
            pool.run_pipeline(run)
        except Exception as e:
            logger.error("L2 parallel DAG failed: %s", e)
            self.recovery.record_failure()
            self.telemetry.record(TelemetryEvent(
                event_type="l2_complete",
                metadata={"success": False, "attempts": 0},
            ))
            return L2Result(success=False, error=str(e))

        reviews = pool.tasks["fanin"].result or {}
        applied = None
        candidates: list[ImprovementCandidate] = []
        eval_results: list[EvalResult] = []
        for review_id in sorted(reviews, key=lambda k: int(k.split("-")[-1])):
            candidate, eval_result = reviews[review_id]
            candidates.append(candidate)
            eval_results.append(eval_result)
            self.telemetry.record(TelemetryEvent(
                event_type="l2_evaluation",
                metadata={"attempt": len(eval_results),
                          "decision": eval_result.decision,
                          "score_avg": eval_result.score_avg},
            ))
            if applied is None and eval_result.passed:
                try:
                    self._apply_improvement(candidate)
                    self.checkpoint.checkpoint(
                        f"l2-applied-{candidate.description[:30]}")
                    applied = candidate
                    self.recovery.reset_failure_count()
                except Exception as e:
                    logger.error("Failed to apply improvement: %s", e)
                    self.recovery.record_failure()

        success = applied is not None
        if not success and budget.expired:
            logger.warning("L2 parallel budget exhausted without success")
            self.recovery.record_failure()

        self.telemetry.record(TelemetryEvent(
            event_type="l2_complete",
            metadata={"success": success, "attempts": len(eval_results)},
        ))
        return L2Result(
            success=success,
            attempts=len(eval_results),
            eval_results=eval_results,
            candidates=candidates,
            applied=applied,
        )

    def _review_candidates(self, goal: str,
                           candidates: list) -> dict:
        """Fan-in: gate every candidate through the immutable evaluator.

        Reviews run through the AgentScheduler (depth=1, cycle-guarded) so
        a repeating coder↔reviewer hand-off aborts instead of spinning.
        """
        sched = AgentScheduler(max_depth=2, cycle_limit=3)
        reviews: dict[str, tuple] = {}

        def handler(task):
            candidate = task.payload["candidate"]
            result = self.evaluator.evaluate({
                "description": candidate.description,
                "target_files": candidate.target_files,
                "diff": candidate.diff_or_code,
                "rationale": candidate.rationale,
                "goal": goal,
            })
            reviews[task.task_id] = (candidate, result)
            return result.decision

        sched.register_agent("reviewer", handler)
        for i, candidate in enumerate(candidates):
            task_id = f"review-{i}"
            queued = sched.submit_task(
                task_id, "reviewer", f"review candidate {i}",
                Priority.MEDIUM,
                payload={"candidate": candidate, "index": i},
                depth=1)
            if not queued:   # guard rejection (depth/cycle) -> fail closed
                reviews[task_id] = (
                    candidate,
                    EvalResult(decision="FAIL",
                               rationale="rejected by scheduler guard"))
        sched.run_event_loop()
        return reviews

    def _dag_event(self, event: dict) -> None:
        """Bridge DAG traceability events into workspace telemetry."""
        self.telemetry.record(TelemetryEvent(
            event_type=event.get("kind", "dag_task"),
            metadata={k: v for k, v in event.items() if k != "kind"},
        ))

    def _generate_candidate(
        self, goal: str, attempt: int, previous_results: list[EvalResult]
    ) -> ImprovementCandidate:
        """Generate an improvement candidate.

        Refines based on previous evaluation results (iterative improvement).
        In production this calls an LLM for code generation.
        """
        refinement_hint = ""
        if previous_results and not previous_results[-1].passed:
            last = previous_results[-1]
            refinement_hint = f" (refinement: {last.rationale[:60]})"
            if last.suggestions:
                refinement_hint += f" — try: {last.suggestions[0]}"

        return ImprovementCandidate(
            description=f"Stub improvement: {goal[:50]}{refinement_hint}",
            target_files=["stub.py"],
            diff_or_code="# Generated improvement stub\npass\n",
            rationale="Stub generation — replace with LLM-based codegen.",
            metadata={"attempt": attempt},
        )

    def _apply_improvement(self, candidate: ImprovementCandidate) -> None:
        """Apply an approved improvement to the workspace."""
        logger.info("Applying improvement: %s", candidate.description)
        for f in candidate.target_files:
            logger.info("  Writing to: %s", f)
            # In production: write the diff/code to the target file
