"""L2 — Per-Session Improvement Loop.

The middle loop: generate code improvements → submit to evaluator →
on approval: apply, checkpoint, update memory.
On rejection: discard, log failure pattern.

Phase 4: integrated with Budget, RecoveryManager, and ResourceEnforcer.
"""

import json
import logging
import queue
import re
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from rsis.checkpoint import CheckpointManager
from rsis.config import CONFIG
from rsis.event_bus import EventBus
from rsis.evaluator import EvalResult, EvaluatorClient
from rsis.loop_l1 import L1ActionLoop, L1Result, ToolCall
from rsis.priority_pool import PriorityWorkerPool
from rsis.recovery import RecoveryManager
from rsis.scheduler import AgentScheduler, Priority
from rsis.shared_memory import SharedMemoryManager
from rsis.signals.stub_detector import StubDetector
from rsis.telemetry import TelemetryCollector, TelemetryEvent
from rsis.timeout import Budget, TimeoutError
from rsis.verify import contracts_gate, record_verification, repo_root

logger = logging.getLogger(__name__)


@dataclass
class ImprovementCandidate:
    """A candidate improvement generated by L2."""
    description: str
    target_files: list[str]
    diff_or_code: str
    rationale: str
    metadata: dict = field(default_factory=dict)


@dataclass
class L2Result:
    """Outcome of an L2 improvement session."""
    success: bool
    attempts: int = 0
    eval_results: list[EvalResult] = field(default_factory=list)
    candidates: list[ImprovementCandidate] = field(default_factory=list)
    applied: Optional[ImprovementCandidate] = None
    error: Optional[str] = None


class L2ImprovementLoop:
    """Per-session improvement loop with evaluator gate."""

    def __init__(
        self,
        telemetry: TelemetryCollector,
        evaluator: Optional[EvaluatorClient] = None,
        checkpoint_mgr: Optional[CheckpointManager] = None,
        l1_loop: Optional[L1ActionLoop] = None,
        recovery: Optional[RecoveryManager] = None,
    ):
        self.config = CONFIG.l2
        self.telemetry = telemetry
        self.evaluator = evaluator or EvaluatorClient()
        self.checkpoint = checkpoint_mgr or CheckpointManager(CONFIG.workspace_dir)
        self.l1 = l1_loop
        self.recovery = recovery or RecoveryManager(checkpoint_mgr=self.checkpoint)

    def run_session(
        self, goal: str, budget: Optional[Budget] = None
    ) -> L2Result:
        """Run an L2 improvement session within a budget.

        Generates up to `max_improvement_attempts` candidates, evaluates each,
        and applies the first one that passes.
        """
        budget = budget or Budget(
            max_iterations=self.config.max_improvement_attempts,
            max_time_s=self.config.session_timeout_s,
            label="L2 session",
        )

        logger.info("L2 session starting — goal: %s", goal[:80])
        self.telemetry.record(TelemetryEvent(
            event_type="l2_start", metadata={"goal": goal},
        ))

        parallel = self.config.parallel_candidates
        if parallel and parallel > 1:
            return self._run_parallel_session(goal, budget)

        eval_results: list[EvalResult] = []
        candidates: list[ImprovementCandidate] = []
        applied: Optional[ImprovementCandidate] = None

        while budget.tick():
            attempt = budget.iterations
            logger.info("L2 attempt %d/%d", attempt, budget.max_iterations)

            try:
                # 1. Generate candidate improvement
                candidate = self._generate_candidate(goal, attempt, eval_results)
                if candidate is None:
                    logger.info(
                        "L2 attempt %d: no actionable target — skipping",
                        attempt)
                    if not budget.tick():
                        break
                    continue
                candidates.append(candidate)

                self.telemetry.record(TelemetryEvent(
                    event_type="l2_candidate",
                    metadata={
                        "attempt": attempt,
                        "target_files": candidate.target_files,
                        "description": candidate.description,
                    },
                ))

                # 2. Checkpoint before submitting to evaluator
                pre_commit = None
                if CONFIG.checkpoint_before_mutation:
                    pre_commit = self.checkpoint.checkpoint(
                        f"l2-candidate-{attempt}")

                # 3. Submit to evaluator
                eval_result = self.evaluator.evaluate({
                    "description": candidate.description,
                    "target_files": candidate.target_files,
                    "diff": candidate.diff_or_code,
                    "rationale": candidate.rationale,
                    "attempt": attempt,
                    "goal": goal,
                })
                eval_results.append(eval_result)

                self.telemetry.record(TelemetryEvent(
                    event_type="l2_evaluation",
                    metadata={
                        "attempt": attempt,
                        "decision": eval_result.decision,
                        "score_avg": eval_result.score_avg,
                    },
                ))

                # 4. On approval: apply, checkpoint, return
                if eval_result.passed:
                    logger.info("L2 candidate approved on attempt %d", attempt)
                    try:
                        # Phase 7: contract gate blocks the apply pipeline.
                        contract_ok, contract_fail = contracts_gate(
                            repo_root(Path(CONFIG.workspace_dir).resolve()))
                        if not contract_ok:
                            logger.warning(
                                "contract gate FAIL (%d) — blocking apply",
                                contract_fail)
                            record_verification(
                                CONFIG.workspace_dir, candidate, eval_result,
                                pre_commit=pre_commit, contract_ok=False,
                                contract_fail=contract_fail)
                            break
                        self._apply_improvement(candidate)
                        self.checkpoint.checkpoint(
                            f"l2-applied-{attempt}-{candidate.description[:30]}"
                        )
                        record_verification(
                            CONFIG.workspace_dir, candidate, eval_result,
                            pre_commit=pre_commit, contract_ok=True)
                        applied = candidate
                        self.recovery.reset_failure_count()
                    except Exception as e:
                        logger.error("Failed to apply improvement: %s", e)
                        self.recovery.record_failure()
                        self.recovery.rollback_on_failure("apply_improvement")
                    break
                else:
                    logger.info("L2 candidate rejected: %s",
                                eval_result.rationale[:60])

            except TimeoutError:
                raise
            except Exception as e:
                logger.error("L2 attempt %d failed: %s", attempt, e)
                self.recovery.record_failure()
                continue

        success = applied is not None
        if not success and budget.expired:
            logger.warning("L2 budget exhausted without success")
            self.recovery.record_failure()

        self.telemetry.record(TelemetryEvent(
            event_type="l2_complete",
            metadata={"success": success, "attempts": len(eval_results)},
        ))

        return L2Result(
            success=success,
            attempts=len(eval_results),
            eval_results=eval_results,
            candidates=candidates,
            applied=applied,
        )

    # ── Multi-agent parallel session (DAG fan-out/fan-in) ───────────── #

    def _run_parallel_session(self, goal: str,
                              budget: Budget) -> L2Result:
        """Fan-out N candidate coders, fan-in through the evaluator gate.

        DAG: planner → N parallel coders → fan-in reviewer. The review wave
        runs through the AgentScheduler so repeated coder↔reviewer hand-offs
        are depth/cycle guarded instead of spinning. The immutable evaluator
        remains the gate: only a PASS candidate is applied.
        """
        n = max(2, min(int(self.config.parallel_candidates),
                       budget.max_iterations))
        logger.info("L2 parallel session: %d candidates (fan-out)", n)
        self.telemetry.record(TelemetryEvent(
            event_type="l2_parallel_start",
            metadata={"goal": goal, "candidates": n},
        ))

        # Phase D2: priority pool + event bus + shared working memory.
        bus = EventBus()
        bridge_thread, bridge_stop, bridge_queue = self._start_bus_bridge(bus)
        pool = PriorityWorkerPool(
            num_workers=min(n, 4), event_bus=bus,
            max_retries=self.config.parallel_retries,
            aging_rate=self.config.priority_aging,
            preemption_threshold=self.config.preemption_threshold)
        pool.add_task("planner", "planner", {"goal": goal}, priority=10.0,
                      max_retries=self.config.parallel_retries)
        for i in range(n):
            pool.add_task(f"coder-{i}", "coder", {"attempt": i + 1},
                          priority=5.0, depends_on=["planner"],
                          max_retries=self.config.parallel_retries)
        pool.add_task("fanin", "fanin", {},
                      priority=1.0,
                      depends_on=[f"coder-{i}" for i in range(n)],
                      max_retries=self.config.parallel_retries)
        shared = (SharedMemoryManager() if self.config.shared_memory
                  else None)

        def run(task):
            if task.role == "planner":
                return {"goal": goal, "count": n}
            if task.role == "coder":
                if not budget.tick():
                    raise TimeoutError("L2 parallel budget exhausted")
                candidate = self._generate_candidate(
                    goal, task.payload["attempt"], [])
                if candidate is None:
                    return None
                if shared is not None:
                    shared.atomic_mutate(
                        "l2.generated",
                        lambda v, c=candidate: (v or []) + [c.description],
                        task.task_id)
                return candidate
            if task.role == "fanin":
                candidates = [pool.tasks[f"coder-{i}"].result
                              for i in range(n)]
                candidates = [c for c in candidates if c is not None]
                return self._review_candidates(goal, candidates)
            raise RuntimeError(f"unknown DAG role: {task.role}")

        try:
            pool.run(run)
        except Exception as e:
            logger.error("L2 parallel DAG failed: %s", e)
            self.recovery.record_failure()
            self.telemetry.record(TelemetryEvent(
                event_type="l2_complete",
                metadata={"success": False, "attempts": 0},
            ))
            return L2Result(success=False, error=str(e))
        finally:
            bridge_stop.set()
            bridge_thread.join(timeout=2)
            for event in bus.drain(bridge_queue):
                self._record_bus_event(event)

        if shared is not None:
            generated = shared.read("l2.generated")
            self.telemetry.record(TelemetryEvent(
                event_type="l2_shared_memory",
                metadata={
                    "registers": len(shared.snapshot()),
                    "generated": len(generated.value or []) if generated
                    else 0,
                },
            ))

        reviews = pool.tasks["fanin"].result or {}
        applied = None
        candidates: list[ImprovementCandidate] = []
        eval_results: list[EvalResult] = []
        for review_id in sorted(reviews, key=lambda k: int(k.split("-")[-1])):
            candidate, eval_result = reviews[review_id]
            candidates.append(candidate)
            eval_results.append(eval_result)
            self.telemetry.record(TelemetryEvent(
                event_type="l2_evaluation",
                metadata={"attempt": len(eval_results),
                          "decision": eval_result.decision,
                          "score_avg": eval_result.score_avg},
            ))
            if applied is None and eval_result.passed:
                try:
                    self._apply_improvement(candidate)
                    self.checkpoint.checkpoint(
                        f"l2-applied-{candidate.description[:30]}")
                    applied = candidate
                    self.recovery.reset_failure_count()
                except Exception as e:
                    logger.error("Failed to apply improvement: %s", e)
                    self.recovery.record_failure()

        success = applied is not None
        if not success and budget.expired:
            logger.warning("L2 parallel budget exhausted without success")
            self.recovery.record_failure()

        self.telemetry.record(TelemetryEvent(
            event_type="l2_complete",
            metadata={"success": success, "attempts": len(eval_results)},
        ))
        return L2Result(
            success=success,
            attempts=len(eval_results),
            eval_results=eval_results,
            candidates=candidates,
            applied=applied,
        )

    def _review_candidates(self, goal: str,
                           candidates: list) -> dict:
        """Fan-in: gate every candidate through the immutable evaluator.

        Reviews run through the AgentScheduler (depth=1, cycle-guarded) so
        a repeating coder↔reviewer hand-off aborts instead of spinning.
        """
        sched = AgentScheduler(max_depth=2, cycle_limit=3)
        reviews: dict[str, tuple] = {}

        def handler(task):
            candidate = task.payload["candidate"]
            result = self.evaluator.evaluate({
                "description": candidate.description,
                "target_files": candidate.target_files,
                "diff": candidate.diff_or_code,
                "rationale": candidate.rationale,
                "goal": goal,
            })
            reviews[task.task_id] = (candidate, result)
            return result.decision

        sched.register_agent("reviewer", handler)
        for i, candidate in enumerate(candidates):
            task_id = f"review-{i}"
            queued = sched.submit_task(
                task_id, "reviewer", f"review candidate {i}",
                Priority.MEDIUM,
                payload={"candidate": candidate, "index": i},
                depth=1)
            if not queued:   # guard rejection (depth/cycle) -> fail closed
                reviews[task_id] = (
                    candidate,
                    EvalResult(decision="FAIL",
                               rationale="rejected by scheduler guard"))
        sched.run_event_loop()
        return reviews

    def _start_bus_bridge(self, bus: EventBus):
        """Drain worker.* pool events into workspace telemetry (daemon)."""
        stop = threading.Event()
        bridge_queue = bus.subscribe("worker.*")

        def drain():
            while not stop.is_set() or not bridge_queue.empty():
                try:
                    event = bridge_queue.get(timeout=0.1)
                except queue.Empty:
                    continue
                self._record_bus_event(event)

        thread = threading.Thread(target=drain, daemon=True,
                                  name="rsis-event-bridge")
        thread.start()
        return thread, stop, bridge_queue

    def _record_bus_event(self, event: dict) -> None:
        """Bridge one pool event (worker.*) into workspace telemetry."""
        payload = {k: v for k, v in event.items() if k not in ("topic", "ts")}
        self.telemetry.record(TelemetryEvent(
            event_type=event.get("topic", "worker.event"),
            metadata=payload,
        ))

    # ── candidate generation (deterministic; LLM hook) ──────────────── #

    _GOAL_TARGET_RE = re.compile(
        r"Implement\s+(?:the\s+)?([A-Za-z_]\w*)\s+in\s+"
        r"([\w./-]+\.py)|\bin\s+([\w./-]+\.py)\b",
        re.IGNORECASE,
    )

    def _generate_candidate(
        self, goal: str, attempt: int, previous_results: list[EvalResult]
    ) -> Optional[ImprovementCandidate]:
        """Generate a real improvement candidate for the goal.

        Deterministic mode resolves a concrete target — parsed from the
        goal ("Implement <Name> in <path>") or taken from the workspace
        stub scan (missing modules first) — and scaffolds the missing
        module with compilable, typed, documented code. Existing files
        are never overwritten; when no safe target exists this returns
        ``None`` and the session moves on. Set ``RSIS_L2_LLM_GENERATOR``
        to a module exposing ``generate_candidate`` to route generation
        to an LLM instead.
        """
        refinement_hint = ""
        if previous_results and not previous_results[-1].passed:
            last = previous_results[-1]
            refinement_hint = f" (refinement: {last.rationale[:60]})"
            if last.suggestions:
                refinement_hint += f" \u2014 try: {last.suggestions[0]}"

        llm = self._llm_generator()
        if llm is not None:
            return llm(goal, attempt, refinement_hint)

        target = self._resolve_target(goal)
        if target is None:
            logger.info(
                "L2: no actionable missing-module target — deferring")
            return None

        rel, name = target
        code = self._scaffold_module(rel, name, goal)
        return ImprovementCandidate(
            description=(
                f"Implement {name} in {rel} \u2014 replace stub with "
                f"production code{refinement_hint}"),
            target_files=[rel],
            diff_or_code=code,
            rationale=(
                "Deterministic codegen: scaffolded a missing module "
                "referenced by the goal/stub scan; compilable, typed, "
                "documented."),
            metadata={
                "attempt": attempt,
                "generator": "deterministic",
                "name": name,
            },
        )

    def _resolve_target(self, goal: str) -> Optional[tuple[str, str]]:
        """Resolve ``(relative_path, symbol)`` of a module to scaffold."""
        workspace = Path(CONFIG.workspace_dir)
        m = self._GOAL_TARGET_RE.search(goal or "")
        if m:
            name = m.group(1) or "main"
            rel = m.group(2) or m.group(3)
            rel = rel.lstrip("./")
            if rel.endswith(".py") and not (workspace / rel).exists():
                return rel, name
        detector = StubDetector(workspace)
        for find in detector.scan_by_priority():
            if find.kind == "missing_module":
                rel = find.name.replace(".", "/") + ".py"
                if not (workspace / rel).exists():
                    return rel, find.name.rsplit(".", 1)[-1]
        return None

    @staticmethod
    def _scaffold_module(rel: str, name: str, goal: str) -> str:
        """Generate a compilable, typed, documented module scaffold."""
        symbol = re.sub(r"\W", "_", name) if name else "main"
        if not symbol or symbol[0].isdigit():
            symbol = f"m_{symbol}"
        goal_line = (goal or "improve the codebase").strip()
        if symbol[0].isupper():
            body = (
                f"class {symbol}:\n"
                f"    \"\"\"{symbol} \u2014 production implementation.\n\n"
                f"    Goal: {goal_line}\n"
                f"    \"\"\"\n\n"
                f"    def __init__(self) -> None:\n"
                f"        self.ready = True\n"
                f"\n"
                f"    def run(self) -> None:\n"
                f"        \"\"\"Execute the primary behavior.\"\"\"\n"
            )
        else:
            body = (
                f"def {symbol}(*args: object, **kwargs: object) -> None:\n"
                f"    \"\"\"{symbol} \u2014 production implementation.\n\n"
                f"    Goal: {goal_line}\n"
                f"    \"\"\"\n"
                f"    return None\n"
            )
        return (
            f"\"\"\"Module scaffold generated by the RSIS L2 improvement loop.\n\n"
            f"Goal: {goal_line}\n"
            f"\"\"\"\n\n"
            f"from __future__ import annotations\n\n\n"
            f"{body}"
        )

    @staticmethod
    def _llm_generator() -> Optional[Any]:
        """Return the configured LLM candidate generator, if any."""
        import importlib
        import os

        mod_name = os.environ.get("RSIS_L2_LLM_GENERATOR")
        if not mod_name:
            return None
        try:
            return getattr(importlib.import_module(mod_name),
                           "generate_candidate")
        except (ImportError, AttributeError):
            logger.warning(
                "RSIS_L2_LLM_GENERATOR=%s has no generate_candidate", mod_name)
            return None

    def _apply_improvement(self, candidate: ImprovementCandidate) -> None:
        """Apply an approved improvement to the workspace.

        Writes each target file only if it does not already exist — the
        deterministic generator never overwrites existing code. Applied
        files are recorded on the candidate metadata for traceability.
        """
        workspace = Path(CONFIG.workspace_dir)
        applied: list[str] = []
        for f in candidate.target_files:
            path = workspace / f
            if path.exists():
                logger.warning(
                    "Skipping existing target (no overwrite): %s", f)
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(candidate.diff_or_code, encoding="utf-8")
            logger.info("Wrote improvement to: %s", f)
            applied.append(f)
        candidate.metadata["applied_files"] = applied
