export const AUTO_ANSWERS = {
  '1.1.1': { text: 'What is the primary domain or field this prompt or project addresses? Describe its scope, core concerns, and any relevant sub-disciplines.', choice: '1.1.1.a' },
  '1.1.2': { text: 'Who is the intended audience for the generated output? What is their baseline familiarity with this domain?', choice: '1.1.2.a' },
  '1.2.1': { text: 'What foundational concepts, theorems, or prior art can the output take for granted? What must be explained from scratch?', choice: '1.2.1.a' },
  '1.2.2': { text: 'At what level of abstraction should the output operate? Should it be concrete and example-driven, or formal and general?', choice: '1.2.2.a' },
  '1.3.1': { text: 'What vocabulary, jargon, or notation should be used or deliberately avoided? Are there established standards the output should follow?', choice: '1.3.1.a' },
  '1.3.2': { text: 'How should complexity be distributed across the output? Should it start simple and deepen, or maintain a consistent level throughout?', choice: '1.3.2.a' },
  '2.1.1': { text: 'What are the primary entities, objects, concepts, or actors that exist in this domain? List them with brief descriptions.', choice: '2.1.1.a' },
  '2.1.2': { text: 'What attributes, properties, or state define each entity? How do entities differ from one another?', choice: '2.1.2.a' },
  '2.1.3': { text: 'What natural categories, types, or groupings organize these entities? Are there clear taxonomies or classification schemes?', choice: '2.1.3.a' },
  '2.2.1': { text: 'Of the entities listed, which are absolutely essential (core) and which are optional, derivative, or contextual (peripheral)?', choice: '2.2.1.a' },
  '2.2.2': { text: 'At what level of granularity should entities be modeled? Should fine distinctions be separate entities or attributes of coarser ones?', choice: '2.2.2.a' },
  '2.2.3': { text: 'How do entities relate to each other in terms of sharing, inheriting, or differentiating attributes?', choice: '2.2.3.a' },
  '2.3.1': { text: 'What are the systemic boundaries of this domain? What is explicitly in scope vs. out of scope?', choice: '2.3.1.a' },
  '2.3.2': { text: 'What external entities, systems, or actors interact with this domain but are not part of it?', choice: '2.3.2.a' },
  '2.3.3': { text: 'What is the lifecycle of each entity? How are they created, modified, combined, retired?', choice: '2.3.3.a' },
  '2.4.1': { text: 'Are there entities that are missing from the model so far? What gaps exist in the current entity list?', choice: '2.4.1.a' },
  '2.4.2': { text: 'Which entities should be merged, split, or reclassified? Are there boundary cases where entity distinctions break down?', choice: '2.4.2.a' },
  '2.4.3': { text: 'What constraints, invariants, or business rules apply to entity instances? What must always be true?', choice: '2.4.3.a' },
  '2.5.1': { text: 'What edge cases, exceptions, or degenerate cases could break the entity model? How should they be handled?', choice: '2.5.1.a' },
  '2.5.2': { text: 'How do entities compose or aggregate into larger structures? Can entities contain or be composed of other entities?', choice: '2.5.2.a' },
  '2.5.3': { text: 'What are the cardinality and multiplicity relationships between entity types? Can an entity have zero, one, or many of another?', choice: '2.5.3.a' },
  '3.1.1': { text: 'What direct associations exist between entities? Which entities reference, point to, or are linked to which others?', choice: '3.1.1.a' },
  '3.1.2': { text: 'What is the nature or type of each association? Is it a use, creation, ownership, or communication link?', choice: '3.1.2.a' },
  '3.2.1': { text: 'What parent-child, containment, or hierarchical relationships exist? Which entities are within, belong to, or are part of others?', choice: '3.2.1.a' },
  '3.2.2': { text: 'What inheritance, specialization, or generalization relationships exist? Which entities are kinds of other entities?', choice: '3.2.2.a' },
  '3.3.1': { text: 'What causal, temporal, or triggering relationships exist? Which entities cause changes in, or are triggered by, others?', choice: '3.3.1.a' },
  '3.3.2': { text: 'What dependency chains, prerequisites, or ordering constraints exist? Must some entities exist before others can be created or used?', choice: '3.3.2.a' },
  '3.4.1': { text: 'What rules govern how relationships can change? Can associations be created, deleted, or modified at any time, or are there restrictions?', choice: '3.4.1.a' },
  '3.4.2': { text: 'How do relationships compose or chain across entities? Can indirect relationships be inferred from direct ones?', choice: '3.4.2.a' },
  '4.1.1': { text: 'What is the overall scope of the procedure or workflow? What does it start from and what is its end state?', choice: '4.1.1.a' },
  '4.1.2': { text: 'How many distinct steps, stages, or phases should the procedure contain? What is the natural breakdown?', choice: '4.1.2.a' },
  '4.2.1': { text: 'Where are the key decision points, branches, or conditional paths? At which steps must a choice be made that affects the rest of the flow?', choice: '4.2.1.a' },
  '4.2.2': { text: 'What are the expected inputs and outputs at each stage? What data or artifacts flow between steps?', choice: '4.2.2.a' },
  '4.3.1': { text: 'What fallback paths, error handling, or recovery procedures should be included for when things go wrong?', choice: '4.3.1.a' },
  '4.3.2': { text: 'How granular should each procedural step be? Should steps be coarse (several actions) or fine (one action per step)?', choice: '4.3.2.a' },
  '5.1.1': { text: 'What hardware platforms or architectures must be supported? (CPU, GPU, mobile, embedded, etc.)', choice: '5.1.1.a' },
  '5.1.2': { text: 'What are the minimum and recommended hardware specs? (RAM, storage, compute, network)', choice: '5.1.2.a' },
  '5.1.3': { text: 'What bandwidth, latency, or networking requirements exist? Is offline operation needed?', choice: '5.1.3.a' },
  '5.1.4': { text: 'What storage infrastructure is needed? (databases, object storage, caching, file systems)', choice: '5.1.4.a' },
  '5.1.5': { text: 'What cloud, on-premise, or hybrid infrastructure is targeted? Are there compliance or sovereignty requirements?', choice: '5.1.5.a' },
  '5.2.1': { text: 'What programming languages, runtimes, or frameworks are required or preferred?', choice: '5.2.1.a' },
  '5.2.2': { text: 'What operating systems and environments must be supported?', choice: '5.2.2.a' },
  '5.2.3': { text: 'What existing libraries, services, APIs, or third-party dependencies should be used or avoided?', choice: '5.2.3.a' },
  '5.2.4': { text: 'What versioning, compatibility, or upgrade policies govern the software stack?', choice: '5.2.4.a' },
  '5.2.5': { text: 'What build systems, CI/CD platforms, and packaging formats are required?', choice: '5.2.5.a' },
  '5.3.1': { text: 'What are the throughput, latency, and concurrency requirements? (requests/sec, response time, simultaneous users)', choice: '5.3.1.a' },
  '5.3.2': { text: 'What data volume and growth rate is expected? (storage size, records, throughput)', choice: '5.3.2.a' },
  '5.3.3': { text: 'What availability, uptime, and disaster recovery targets are required?', choice: '5.3.3.a' },
  '5.3.4': { text: 'What scalability model is required? (vertical, horizontal, elastic, serverless)', choice: '5.3.4.a' },
  '5.3.5': { text: 'What security and compliance standards must be met? (auth, encryption, audit, regulations)', choice: '5.3.5.a' },
  '5.4.1': { text: 'What external systems, APIs, or services must this system integrate with?', choice: '5.4.1.a' },
  '5.4.2': { text: 'What integration protocols, data formats, or standards must be supported?', choice: '5.4.2.a' },
  '5.4.3': { text: 'What is the expected timeline, milestones, and delivery cadence?', choice: '5.4.3.a' },
  '5.4.4': { text: 'What testing, staging, and rollout strategy is required?', choice: '5.4.4.a' },
  '5.4.5': { text: 'What documentation, training, or knowledge transfer outputs are expected alongside the system?', choice: '5.4.5.a' },
  '6.1.1': { text: 'What development process or methodology best fits this project? How should work be planned and tracked?', choice: '6.1.1.a' },
  '6.1.2': { text: 'What is the expected team size, composition, and structure?', choice: '6.1.2.a' },
  '6.2.1': { text: 'What code review, testing, and quality assurance practices should be followed?', choice: '6.2.1.a' },
  '6.2.2': { text: 'How should the team handle technical debt, refactoring, and code quality?', choice: '6.2.2.a' },
  '6.3.1': { text: 'How should the team communicate, share knowledge, and manage decisions?', choice: '6.3.1.a' },
  '6.3.2': { text: 'What is the decision-making and escalation process? How are architectural choices made?', choice: '6.3.2.a' },
  '7.1.1': { text: 'How should the system be deployed, released, and updated in production?', choice: '7.1.1.a' },
  '7.1.2': { text: 'What environment and release management strategy should be used?', choice: '7.1.2.a' },
  '7.2.1': { text: 'What logging, monitoring, alerting, and observability infrastructure is needed?', choice: '7.2.1.a' },
  '7.2.2': { text: 'What configuration and feature management approach should be used at runtime?', choice: '7.2.2.a' },
  '7.3.1': { text: 'What maintenance schedule, upgrade policy, and lifecycle management is expected?', choice: '7.3.1.a' },
  '7.3.2': { text: 'What is the long-term stewardship plan? Who owns the system after initial delivery?', choice: '7.3.2.a' },
};
